### ISSUE TITLE
SMC - Prod Listing Not Loading

### ISSUE THREAD

**Issue by ColinBuyck** [housingbayarea/bloom#605] opened 2023-03-27 17:28 UTC
The listing at the following link doesn't load : https://smc.housingbayarea.org/listing/d735cdb0-24f9-4812-ae54-c0128f49cf57/2000_delaware_2000_south_delaware_san_mateo_ca

Technical Notes:
- No activity in network tab for an fetch/xhr request
- The data comes back correctly from [netlify](https://smc.housingbayarea.org/_next/data/GNt0wafbYzPLvcHCnHBZ8/en/listing/d735cdb0-24f9-4812-ae54-c0128f49cf57/2000_delaware_2000_south_delaware_san_mateo_ca.json?id=d735cdb0-24f9-4812-ae54-c0128f49cf57&slug=2000_delaware_2000_south_delaware_san_mateo_ca)
- A redeploy of the site did not fix the issue

**Comment by emilyjablonski** [comment] 2023-03-31 18:35
This is now fixed. There were some weird hidden characters in the required documents field that our markdown package was getting very uphappy about, it seems like the problem was specific to that package - I just removed extra new lines / tabs and all is now well. Not yet sure how to prevent this in the future.

**Comment by sarahlazarich** [comment] 2023-04-10 20:54
Dev was not able to reproduce this outside of this issue. When you copy/paste the exact same text string that was causing issues before it is working, so there is some sort of special character that was in the string that you can't copy over. This leads us to believe it actually wasn’t a problem with the package but with the specific string.

**Closed by sarahlazarich** 2023-04-10 20:54 UTC
Labels: bug
